apiVersion: v1
kind: Service

metadata:
  name: nwl16-devops-service
  labels:
    app: nwl16-devops

spec:
  selector:
    app: nwl16-devops
  type: 'ClusterIP'
  ports:
    - name: nwl16-devops-service
      port: 80
      targetPort: 8080
      protocol: TCP
