name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: 'Run tests'
        run: go test

      # pegar último commit dinâmico
      - name: 'Generate SHA'
        id: 'generate_sha'
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      # logar no container registry
      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v3'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # utiliza commit
      - name: 'Build docker image'
        run: docker build -t brenoo2018/nwl16-devops:${{ steps.generate_sha.outputs.sha }} .

      # enviar imagem pro container registry
      - name: 'Build and Push'
        uses: 'docker/build-push-action@v6'
        with:
          context: .
          push: true
          tags: |
            brenoo2018/nwl16-devops:${{ steps.generate_sha.outputs.sha }}
            brenoo2018/nwl16-devops:latest
      # - name: 'Push docker image'
      #   run: |
      #     docker push brenoo2018/nwl16-devops:${{ steps.generate_sha.outputs.sha }}
      #     docker tag brenoo2018/nwl16-devops:${{ steps.generate_sha.outputs.sha }} brenoo2018/nwl16-devops:latest
      #     docker push brenoo2018/nwl16-devops:latest

      - name: 'Update Image Helm'
        uses: 'fjogeleit/yaml-update-action@main'
        with:
          branch: release
          targetBranch: main
          createPR: true
          valueFile: 'deploy/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          message: 'New: Update tag in values helm'
